[build]
  command = "npm ci || npm install && npm run build"
  publish = "dist"
  

  [build.environment]
    NODE_VERSION = "18.20.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[redirects]]
  from = "/api/*"
  to = "https://devdeakinapp-1.onrender.com/:splat"
  status = 200
  force = true
