[build]
  # Build the client app from the repo root using the client workspace
  command = "npm --prefix client ci || npm --prefix client install && npm --prefix client run build"
  publish = "client/dist"

[build.environment]
  # Pin Node for consistent builds
  NODE_VERSION = "18.20.3"


[[redirects]]
  from = "/api/create-payment-intent"
  to   = "https://devdeakinapp.onrender.com/create-payment-intent"
  status = 200
  force  = true

# --- Generic API proxy, keep /api prefix for all other endpoints ---
[[redirects]]
 
  from = "/api/*"
  to   = "https://devdeakinapp.onrender.com/:splat"
  status = 200
  force  = true


[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
