[build]
  command = "npm run build"      
  publish = "client/dist"        
  [build.environment]
    NODE_VERSION = "18.20.3"     

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://<your-render-domain>/:splat"
  status = 200
  force = true
